image: docker:stable
services:
- docker:dind

stages:
- build
- test
- release
# - deploy

variables:
  IMAGE_TAG_SHA: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  DOCKER_DRIVER: overlay2

before_script:
  - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com"

build:
  stage: build
  script:
    - docker pull $IMAGE_TAG_LATEST || true
    - docker build --cache-from $IMAGE_TAG_LATEST --pull -t $IMAGE_TAG_SHA .
    - docker push $IMAGE_TAG_SHA

test:
  stage: test
  environment:
    - ENV_SILENT=true
    - DRIVE_DISK=s3
  script:
    - docker pull $IMAGE_TAG_SHA
    - docker run $IMAGE_TAG_SHA node /home/node/api/ace test

release-image:
  stage: release
  script:
    - docker pull $IMAGE_TAG_SHA
    - docker tag $IMAGE_TAG_SHA $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG_LATEST
  only:
    - master

# deploy:
#   stage: deploy
#   script:
#     - ./deploy.sh
#   only:
#     - master
